# https://www.appveyor.com/docs/appveyor-yml/

# Test against these versions of Node.js.
environment:
  MOCHA_REPORTER: 'mocha-appveyor-reporter'
  matrix:
    - nodejs_version: '6'

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - ps: npm install -g pnpm
  - appveyor-retry pnpm install
  - appveyor-retry pnpm add mocha-appveyor-reporter # must be installed locally.

cache:
  - '%LOCALAPPDATA%\pnpm'

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - git rev-parse HEAD
  - pnpm run build:node
  - pnpm run build:test
  - cmd: pnpm run test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: '{build}'
